### ISSUE TITLE
TODO list before initial deployment

### ISSUE THREAD

**Issue by bartoszreszka** [bartoszreszka/lighting-chart#26]
# TODO list

Things that need to be done:

- [x] Add version number in GUI
- [x] Move to [Apache License 2.0](https://www.apache.org/licenses/LICENSE-2.0)
- [x] Refactor 'Download latest version'
- [x] ~~Add time zone indicator~~
- [x] EXE file

**Comment by bartoszreszka** [comment]
All done.
